apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment1
  labels:
    app: my-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
      # You might also put the annotation here if the webhook primarily affects Pods,
      # but if you're ignoring mutations to the Deployment object itself,
      # it typically goes on the Deployment metadata.
      # annotations:
      #   client.lifecycle.config.k8s.io/mutation: ignore
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3 # Using a specific tag to avoid 'latest' issues
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
